name: async_resource
description: Automatically cache network resources and use them when offline. Interface with local resources on any platform.
version: 0.1.4
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/async_resource

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.0.0
  path: ^1.0.0
  service_worker: ^0.2.0
  rxdart: ^0.18.0

dev_dependencies:
  mockito: ^3.0.0
  test: ^1.0.0
